### ISSUE TITLE
Cannot add new review while offline

### ISSUE THREAD

**Issue by anthumchris** [kathleenwest/mws-restaurant-stage-3-kew#1]
Tested with Chrome 69 at http://localhost:8000/.  Ensure "preserve log" is checked in console options.

**Reproduction steps:**
1. Open http://localhost:8000/restaurant.html?id=1
1. Open DevTools, Application Tab, "Clear Storage" pane.
1. click "Clear Site Data"
1. Refresh Page
1. In DevTools Network tab, enable "offline" checkbox
1. Click "Add Review" on page.
1. Enter "name" for name and "comments" for comments. Leave rating at 1.
1. Click Submit
1. The page refreshes and displays error "This site can’t be reached". DevTools Console shows error `Uncaught (in promise) TypeError: Failed to fetch  sw.js:1`

**Comment by kathleenwest** [comment]
So I figured out one clue.  The offline review add feature works correctly ...but only if you start your app at http://localhost:8000/ first..., ... then navigate to the restaurant..., enter offline, add the review, come back online. IF you start on the restaurant page without first visiting the root site, all hell starts when trying to add a review in offline mode. I'm going to look further into figuring this out and trying to fix that bug. I never thought to test the offline feature from starting at a restaurant page first. Very good catch!  

The second reviewer/grader passed me, but I'm going to try and address this bug in a future update because i want to try and be puuuurfect. :) 

Thanks for your help, let me know if you find anything else.

**Comment by kathleenwest** [comment]
Thank you for reporting. I spent some time working on the issue. The new updated code has a fix to the issue and I reproduced your test steps to verify it is working as expected now. I will soon be recording a youtube video of the offline capability of the site. If you want to verify this fix, you can download the updated code repo here and let me know if you see this or any other critical issues.
